id: P006974
initial_creation_type: ocr
source_metadata:
  id: bdr:W21896
  title: བདུད་གླིང་གཡུལ་འགྱེད
  author: ''
  volumes:
    3afe348aac564b2f8db76355df7a4f61:
      image_group_id: I4763
      title: ''
      volume_number: 1
      total_pages: 776
      base_file: v001.txt
ebook_metadata:
  title: བདུད་གླིང་གཡུལ་འགྱེད
  author: ''
  sku: P006974
  cover: cover.jpg
  layers:
  - pagination
