id: I68A97DD6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:30:10+00:00'
last_modified: '2022-06-08T09:41:13.461841+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21896
  title: བདུད་གླིང་གཡུལ་འགྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D7A5:
      image_group_id: I4763
      title: ''
      total_pages: 776
      order: 1
      base_file: D7A5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
